### ISSUE TITLE
Moved to Main Menu after using Portal

### ISSUE THREAD

**Issue by Senfdeckel** [lunar91/CrossServerPortals#1]
hello. i have the issue that im just being moved to main menu after using the Portal and then nothing happens.

help would be very appreciated

**Comment by lunar91** [comment]
Are you using Steam? What platform do you have the game on?

**Comment by Senfdeckel** [comment]
Im using Steam

**Comment by lunar91** [comment]
Thanks for reporting. The update on October 5 appears to have refactored how some menus work and when Steam networking is loaded. This has been fixed with [v0.1.1](https://github.com/lunar91/CrossServerPortals/releases/tag/v0.1.1).
