### ISSUE TITLE
Mod Compatibility

### ISSUE THREAD

**Issue by Balatuc** [lunar91/CrossServerPortals#2]
Does this mod work with TargetPortal?

**Comment by lunar91** [comment]
I don't think so. At a glance, TargetPortal implements its own teleportation. CrossServerPortals relies on the game's teleportation implementation, and therefore would likely not run.

Try it and let me know.

**Comment by SElHorstwes** [comment]
Hello, I am testing it on my server, and it doesn't work with the target portal. It would be very interesting if it worked.

**Comment by ConSolatory** [comment]
> Hello, I am testing it on my server, and it doesn't work with the target portal. It would be very interesting if it worked.

+1
