### ISSUE TITLE
No Issue - Advice 

### ISSUE THREAD

**Issue by MrBungled** [lunar91/CrossServerPortals#3]
Hi Lunar 

I have been successfully using your mod for 6-8 months now and passing between my servers has been fantastic. A great mod. 

I have with help of valheim wizard from vwe discord to make a Cross Server Portal Hub. It currently has 4 hub nodes with a central market hub. Supporting roughly 56 server Hosts worlds.  We post signs for password or mods required. As the hub itself is fully vanilla besides cross server portals and portal everything mod. They seem to work together well. 

Our goal is to have a subway station of sorts with traffic coming and going from the nodes which would be region specific nodes like a NA and EU node … as well as a modded node ( as long as it’s not too many mods you can’t get into the vanilla hub )  as well as a Vanilla node. All with the central market hub as a pass through. 

Currently hosting 10 cross server portals to hosts around the world at the moment in its infancy… concept was just thought of a couple weeks ago.  

I was checking to see if you had advice for the hub live concept.

Also hoping that you can keep this awesome mod updated and alive throughout Valheims updates. For your review … Hub address is 142.161.183.45:27007 no pw required. 

Much appreciated 

MrBungles

**Comment by lunar91** [comment]
MrBungles,

That's an interesting concept that I hadn't even considered.

My setup has only 3 servers: a primary server with our main builds, resources, etc.; a secondary server with some older builds that we don't really use as much anymore; and a third server which we periodically re-generate the world for exploration with each new update.

I was not able to connect to your hub world. It would be interesting to see where this idea goes. Let me know if/when you get the hub world up again.

**Comment by MrBungled** [comment]
Hey hey

The Hub is up 24/7 , but IP might have changed since . It is 160.202.165.30:27007 no password required.

However if you have potentially vanilla breaking entry into servers that would be probably be why you couldn’t get into the server or ip . Definitely no problem with QOL mods very lightly modded shouldn’t impact entry into the Hub

I would love to have portals to your worlds if you’re allowing public traffic ? And are r heavily modded . The hub will provide traffic to them.

Let me know what you think

Cheers



On Jul 27, 2024, at 12:13 AM, lunar91 ***@***.***> wrote:

﻿

MrBungles,

That's an interesting concept that I hadn't even considered.

My setup has only 3 servers: a primary server with our main builds, resources, etc.; a secondary server with some older builds that we don't really use as much anymore; and a third server which we periodically re-generate the world for exploration with each new update.

I was not able to connect to your hub world. It would be interesting to see where this idea goes. Let me know if/when you get the hub world up again.

**Comment by MrBungled** [comment]
Sorry meant to say below … that if your servers or clients are heavily modded you likely won’t be able to gain access to the hub. I tested with a server host for a few hours a while back and his server has 42 mods , so in order for him to enter the hub he had to disable 14 of them. Lol but then walking through the cross server portals to his world he was denied Access without those mods . But was a fun tests none the less.



On Jul 27, 2024, at 2:02 AM, Gordon Sayer ***@***.***> wrote:

﻿
Hey hey

The Hub is up 24/7 , but IP might have changed since . It is 160.202.165.30:27007 no password required.

However if you have potentially vanilla breaking entry into servers that would be probably be why you couldn’t get into the server or ip . Definitely no problem with QOL mods very lightly modded shouldn’t impact entry into the Hub

I would love to have portals to your worlds if you’re allowing public traffic ? And are r heavily modded . The hub will provide traffic to them.

Let me know what you think

Cheers



On Jul 27, 2024, at 12:13 AM, lunar91 ***@***.***> wrote:

﻿

MrBungles,

That's an interesting concept that I hadn't even considered.

My setup has only 3 servers: a primary server with our main builds, resources, etc.; a secondary server with some older builds that we don't really use as much anymore; and a third server which we periodically re-generate the world for exploration with each new update.

I was not able to connect to your hub world. It would be interesting to see where this idea goes. Let me know if/when you get the hub world up again.

**Comment by lunar91** [comment]
The hub world looks great! Thanks for sharing!

My servers are all private with a small group only, so I don't think they'd be suitable for your setup, but if I hear of any that would I'll recommend them to you.

**Comment by MrBungled** [comment]
Hey Lunar

Thanks for the great feedback!

The nice thing about the Hub is your server portal can still be private , password protected and even if you have a whitelist it still applies. As an example I have my private shared world in there called Grundle, but no password is posted so it is private and I now only give my private group the IP to the Hub so they have to go through the cross server portals to get there. Lol …Just a way to increase traffic flow in the subway system. Hoping to see a hub of activity flowing through eventually.

So for yourself and your patrons of your servers could do the same, especially if you have a few different ones on the go , it gives you the ability to walk in one portal to another etc. pretty cool convenience for sure. They don’t have to be full vanilla either as an example I run with about 15 mods all client side QOL mods and still considered vanilla to the hub entry and any vanilla server. Only clients need the xsp mod , but if you do put it server side for the return portal to the Hub , the nice thing is the mod does g impose a server entry restriction… which is awesome too.

Thanks again for your input and would be my pleasure to have a portal setup to your world there, if only for yourself even 😉

Cheers




On Jul 30, 2024, at 1:23 AM, lunar91 ***@***.***> wrote:

﻿

The hub world looks great! Thanks for sharing!

My servers are all private with a small group only, so I don't think they'd be suitable for your setup, but if I hear of any that would I'll recommend them to you.

**Comment by jaycenornin** [comment]
I know this is closed and more of a discussion than anything, but I wanted to add a thought that seems related. 
Yesterday I thought of making a Stargate mod. One aspect of it would be to integrate this cross-server portal functionality and allow people to create a "gate network" of valheim worlds very similar to the hub mentioned above. 

Just wanted to say that this mod potentially enables some amazing and cool community-building within the game that it otherwise couldn't support. I don't know if I have the bandwidth for making a Stargate mod right now, but in the future I may come back and ask for permission to fork CrossServerPortals for use with it.
