### ISSUE TITLE
Dverger portal trouble

### ISSUE THREAD

**Issue by MrBungled** [lunar91/CrossServerPortals#4]
Noticed on my server that had a few Dverger portals placed. I had the cross server portals mod installed on my client side ( not on server side ) it gave an error message in console about color when in range of the dverger portals , sorry don’t have exact info on the error. Ultimately the mod causes the dverger portals to not work at all. Not sure if that’s the way it’s always been or since Bog witch update.As I had only seen the dverger portals work with their own animations before. Was only once I installed the cross server portals mod that the error occurred and also disappeared removing the mod. 

just a heads up. 

Thanks for the great mod ! Keep it rockin! 

Cheers!

**Comment by lunar91** [comment]
I'm unable to replicate the issue. 

This mod doesn't use any custom animations. It just shifts the colors by modifying variables on the existing animations.

Can you post errors that show up in the `Valheim\BepInEx\LogOutput.log` file?

Might be conflict with another mod. What other mods are you using?

**Comment by MrBungled** [comment]
Good day,

Currently mostly using Jeres mods , infinity hammer , server dev commands, extended world prefabs, world edit commands, upgrade world And was using comfy gizmo, and jotunn, more vanilla prefabs and sears catalog… no other mods that alter portals other than cross server portals

However at the time of the errors is was only specific to the dverger portals . They typically aren’t vanilla placeable. They need to be spawned in, or hammer placed. The dverger portals have a different sound and animation that seemed to throw errors when near them, also stopped them from working all together. Took the xsp mod out and they worked as intended.

Sadly I didn’t copy the error. However next time I see it i will copy it and send to you. I will try to replicate the scenario and see.

Thanks again and I will see if I can replicate it by going into that server with those type of portals.



On Nov 14, 2024, at 11:40 PM, lunar91 ***@***.***> wrote:

﻿

I'm unable to replicate the issue.

This mod doesn't use any custom animations. It just shifts the colors by modifying variables on the existing animations.

Can you post errors that show up in the Valheim\BepInEx\LogOutput.log file?

Might be conflict with another mod. What other mods are you using?

**Comment by MrBungled** [comment]
Sorry Meant to send you the log output as well. Which is esssentially the same as the screen shot of the console errors.

[Info   : Unity Log] 11/15/2024 07:10:23: Placed portal

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Lunarbin.Valheim.CrossServerPortals.CrossServerPortals.SetPortalColors (TeleportWorld portal, System.Boolean defaultColors) (at <51761b7753a94715810e4fc30edc2639>:0)
Lunarbin.Valheim.CrossServerPortals.CrossServerPortals+PatchTeleportWorldHaveTarget.Prefix (System.Boolean& __result, TeleportWorld __instance) (at <51761b7753a94715810e4fc30edc2639>:0)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::HaveTarget>(TeleportWorld)
TeleportWorld.Awake () (at <94a8ab08dca748d3beb540d5228ac7b0>:0)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
Player:DMD<Player::PlacePiece>(Player, Piece, Vector3, Quaternion, Boolean)
Player:TryPlacePiece(Piece)
Player:DMD<Player::UpdatePlacement>(Player, Boolean, Single)
Player:DMD<Player::Update>(Player)

[Info   : Unity Log] 11/15/2024 07:10:23: Disabling TELEPORT  character_trigger

[Info   : Unity Log] 11/15/2024 07:10:23: Disabling PlayerBase  character_trigger

[Info   : Unity Log] 11/15/2024 07:10:23: Disabling TELEPORT  character_trigger

[Info   : Unity Log] 11/15/2024 07:10:23: Disabling PlayerBase  character_trigger

[Info   : Unity Log] 11/15/2024 07:10:24: Activating default element Continue

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Lunarbin.Valheim.CrossServerPortals.CrossServerPortals.SetPortalColors (TeleportWorld portal, System.Boolean defaultColors) (at <51761b7753a94715810e4fc30edc2639>:0)
Lunarbin.Valheim.CrossServerPortals.CrossServerPortals+PatchTeleportWorldHaveTarget.Prefix (System.Boolean& __result, TeleportWorld __instance) (at <51761b7753a94715810e4fc30edc2639>:0)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::HaveTarget>(TeleportWorld)
TeleportWorld.GetHoverText () (at <94a8ab08dca748d3beb540d5228ac7b0>:0)
(wrapper dynamic-method) Hud.DMD<Hud::UpdateCrosshair>(Hud,Player,single)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)

________________________________

**Comment by MrBungled** [comment]
Good day,

Just checking in to see what you thought about the error, and also to provide you an address as I had done before to HubHeim The Cross Server Portal World.... this is a newer HubHeim Deployment iteration and Live as of Today.  address to it  207.161.61.46:27007   no password required

I went into one server today to test it ... its in the HubHeim Hub Node 1 ... Called RPG World , as soon as you enter the server it spams the console with an error about cross server portals .. i believe a similar error as to the previous message log i sent. However, this is just immediately upon entry into that server. I do not see any dverger portals around , so not sure what is causing the error from this server. However it is clearly erroring from the dverger portals ... as soon as I place one the error pops.

Let me know what you think and if you need any testing.

Cheers

MrBungles
aka unitrelative

________________________________

**Comment by MrBungled** [comment]
Awesome ! Great work!

Thanks



On Nov 20, 2024, at 12:50 PM, lunar91 ***@***.***> wrote:

﻿

I wasn't aware there was a third spawnable portal in the game. I'm able to replicate the problem now and am looking into it.

**Comment by lunar91** [comment]
I just pushed [v0.3.1 release](https://github.com/lunar91/CrossServerPortals/releases/tag/v0.3.1). This disables custom colors if it cannot find the appropriate components to color, such as with Dverger portals. Will update Thunderstore later today.

I may color those portals at some point in a future release.

**Comment by MrBungled** [comment]
That’s awesome ! Nice quick work.

I know the dverger portals themselves use a unique color and animation and sound as well. It’s quite nice actually.

I have been using your mod so long now that whenever I did see or place a dverger portal they never worked, I just assumed they were only a show piece. Until a few weeks ago I unloaded all my mods testing in a server and noticed the portals working. Then applied the mod and they didn’t work. Which lead me to the path of reaching out to you.

In your newly updated mod will the dverger portals work now ? With their standard animation etc ?

Thanks again

Cheers




On Nov 20, 2024, at 1:27 PM, lunar91 ***@***.***> wrote:

﻿

I just pushed v0.3.1 release<https://github.com/lunar91/CrossServerPortals/releases/tag/v0.3.1>. This disables custom colors if it cannot find the appropriate components to color, such as with Dverger portals. Will update Thunderstore later today.

I may color those portals at some point in a future release.

**Comment by lunar91** [comment]
Yes. In my testing, they functioned the same as without mods.

Dverger portals set up as cross server portals will work, but the portals themselves will look the same as the base game portal (blue glyphs and blue portal animation, with the separate portal sound). The custom colors I applied to portal animations and glyphs to make cross server portals stand out from the others will not apply to Dverger portals.

**Comment by MrBungled** [comment]
Perfect workaround for now ! Wtg

Love your new color adds to the last update, makes the glyphs pop ! Very nice animation colors too.

Of course if I notice anything else I’ll reach out.

Much appreciated

Take care


On Nov 20, 2024, at 1:58 PM, lunar91 ***@***.***> wrote:

﻿

Yes. In my testing, they functioned the same as without mods.

Dverger portals set up as cross server portals will work, but the portals themselves will look the same as the base game portal (blue glyphs and blue portal animation, with the separate portal sound). The custom colors I applied to portal animations and glyphs to make cross server portals stand out from the others will not apply to Dverger portals.

**Comment by MrBungled** [comment]
All looks to be working as intended. Thank you again

One item to note ... for let say dead portals, that no longer have a valid connection. When you walk through the portal. it puts you in a log out log in state loop. Endlessly .... is there a wat for it to close the connection and push you at least to the menu screen after the unable to connect or invalid version error when trying to connect. Or sometimes that server just isnt online at that moment.  However it does the log in logout infinite loop until you force quit the game.

Not sure if theres anything you can do on your end for that in the next iteration or if its just a byproduct of not being able to connect via the portal being dead.


Thanks again for the good work.

Cheers!


________________________________
